#!/bin/bash
images=$(grep -rE "image" . --include="docker-compose.*" --include="compose.*" 2> /dev/null | awk -F ": " '{print $3}')
need_update=()
for image in $images; do
  echo "$image"
  running=$(docker ps --filter "ancestor=${image//\"/}" --format "{{.Names}}")
  if [[ ! -z $running ]]; then
    docker pull ${image//\"/}
    updated=$(docker ps --filter "ancestor=${image//\"/}" --format '{{.ID}}')
    if [[ -z $updated ]]; then
      need_update+=($running)
    fi
  else
    echo "No container running for $image"
  fi
done

echo Need update: ${#need_update[@]} images
if [[ ${#need_update[@]} > 0 ]]; then
  for container in $need_update; do
    working_dir=$(docker inspect "$container" --format='{{index .Config.Labels "com.docker.compose.project.working_dir"}}')
    docker compose -f $working_dir/*.y*l up -d
  done
fi
