#!/bin/bash

#COLORS
txtrst=$(tput sgr0) # Text reset
txtblu=$(tput setaf 4) # Blue
txtgrn=$(tput setaf 2) # Green
txtylw=$(tput setaf 3) # Yellow

M2SETTINGS=$HOME/.m2/settings.xml

read_passwd() {
    read -s PASSWD
}

gen_passwd_hash() {
    echo "${txtgrn}Generating password hash..."
    HASH=$(mvn --encrypt-password $PASSWD | awk 'NR==1{gsub("\/", "\\/"); print}' 2>/dev/null)
    echo "${txtylw}HASH: ${txtrst}" $HASH
}

get_old_hash() {
    echo "${txtgrn}Search current hashes..."
    OLD_HASH=$(grep '<password>{' $M2SETTINGS | awk 'NR==1{sub("<password>", ""); sub("</password>", ""); gsub(/^[ \t]+/,"");
	gsub("\/", "\\/"); print}' 2>/dev/null) 
    echo "${txtylw}OLD HASH: ${txtrst}" $OLD_HASH
}

sed_settings() {
    echo "${txtgrn}Update settings file..."
    get_old_hash
    echo "${txtgrn}Updating hashes..."
    sed -i "s|$OLD_HASH|$HASH|g" $M2SETTINGS
    echo "${txtblu}New settings: ${txtrst}"
    grep '<password>{' $M2SETTINGS
}


echo ""
echo "${txtblu}Maven Change Password"
echo ""

echo "${txtgrn}Enter new password..."
read_passwd

gen_passwd_hash
sed_settings
