#!/bin/sh
cams=$(printenv | awk -F "=" '$1 ~ "^CAM_" {print $1}' | awk -F "_" '{print $2}')
rec_path=/mnt/cctv/records

echo "Last files:"
for cam in $cams; do
  echo $cam: $(find ${rec_path}/$cam -name "*.mkv" | sort -n | tail -n1)
done

echo "----------------------------------------------------"
echo "Active records:"
active=$(find "$rec_path" -type f -name "*.mkv" -cmin .5 | awk -F "/" '{print $5}')
for act in $active; do
  echo " - $act"
done
#find $rec_path -name "*.mp4" -cmin .1

echo "----------------------------------------------------"
echo "Restart count and date:"
docker ps --filter "label=cctv" --format "{{.Names}}" | xargs docker inspect --format "{{.Name}} {{.RestartCount}} {{.State.StartedAt}}"

echo "----------------------------------------------------"
echo "Filesystem available space:"
df -h "$rec_path" | tail -n 2

